name: Publish pg-ulid image to GHCR

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build & push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get UTC timestamp
        id: timestamp
        run: echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/pg-ulid:latest
            ghcr.io/${{ github.repository_owner }}/pg-ulid:${{ github.sha }}
          build-args: |
            GITHUB_REPOSITORY=${{ github.repository }}
            BUILD_DATE=${{ steps.timestamp.outputs.BUILD_DATE }}
